# Generated by Django 4.2.6 on 2024-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام کاربر')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام خانوادگی کاربر')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل کاربر')),
                ('password', models.CharField(max_length=128, verbose_name='رمز عبور')),
                ('level', models.CharField(blank=True, choices=[('normal', 'کاربرعادی'), ('vip', 'کاربر ویژه')], max_length=30, null=True, verbose_name='سطح کاربر')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('email_active_code', models.CharField(max_length=100, verbose_name='کد فعال سازی ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='نشانی کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'user',
            },
        ),
    ]
