services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eshop
      MYSQL_USER: eshop
      MYSQL_PASSWORD: eshop
    networks:
      - main
    ports:
      - "3306:3306"
    restart: always


  redis:
    container_name: redis
    image: redis:latest
    networks:
      - main
    ports:
      - "6379:6379"  
    restart: always

  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn eshop.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
      - static:/code/static
      - uploads:/code/uploads
    expose:
      - "8000"
    networks:
      - main
    depends_on:
      - mysql  
    restart: always
  
  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/app/static
      - uploads:/app/uploads

networks:
  main:

volumes:
  static:
  uploads: